### ISSUE TITLE
Please provide end-to-end examples

### ISSUE THREAD

**Issue by kartiksura** [linkedin/goavro#1]
Please provide a basic tutorial to use the package, maybe on the lines of http://avro.apache.org/docs/1.7.7/gettingstartedjava.html

I am specially interested Serializing multiple objects in a file.

**Comment by karrick** [comment]
I have updated goavro's README with a limitations section. The plan is to implement helper routings in goavro that handle Avro Object Container Files. I have written code that does this, including compression handling, but removed the methods from the official release until I get a better grip on what that API should look like.

I'm open to how others think the API should look like.

Any suggestions?

**Comment by karrick** [comment]
I didn't want to leave you hanging for your original question, about having end-to-end examples for encoding data.

Not only does the README.md file have examples for creating codecs, encoding, and decoding data, the test files in the repository provide numerous examples of encoding and decoding data using goavro.

**Comment by pm-kartik-sura** [comment]
There are test cases but there isnt a single example to use the library easily. I would love to see examples for:
1. Defining a simple schema and encoding and decoding the object
2. Defining a complex schema and ecoding and decoding the object

Something on the lines of https://github.com/stealthly/go-avro/tree/master/examples would help me in a big way.

**Comment by karrick** [comment]
I have added a few examples that demonstrate encoding and decoding both simple and complex schema, including nested records.

Thanks for your feedback about missing examples. I hope these help.

**Comment by karrick** [comment]
By the way, I'll leave this issue open until I have file API also included in goavro, along with examples.

If you'd like to see any additional examples, please feel free to ask.

**Comment by pm-kartik-sura** [comment]
Excellent examples.
 I was able to serialize complex use cases such as:
1. record in a record
2. Array of records in a record
3. Arrays

**Comment by karrick** [comment]
I have added a few examples in the examples directory, updated the README.md with examples, and added additional examples in godoc.

Please let me know if you have any additional examples you'd like to see.
