### ISSUE TITLE
Support Single Object Encoding

### ISSUE THREAD

**Issue by bka9** [linkedin/goavro#107]
In the latest Avro specification they detail a single object encoding pattern. Other language libraries have this implemented and it would be nice to have in goavro.

https://avro.apache.org/docs/1.8.2/spec.html#single_object_encoding

**Comment by karrick** [comment]
This is a great suggestion. Unfortunately I cannot do this until we have the CRC-64-AVRO fingerprint work completed.

**Comment by karrick** [comment]
Requires #35

**Comment by tsutsu** [comment]
Since the code for both emitting parsing canonical forms and CRC-64-AVRO fingerprints are now merged, can progress be made on this?

**Comment by tsutsu** [comment]
Examining further, it looks like the only thing needed to achieve a Single-Object Encoding at this point is to copy the `RawFromNative` and `NativeFromRaw` functions (and supporting tests) from @bka9 's fork.

**Comment by karrick** [comment]
There is a bit more work to be done. Working on that now...

**Comment by karrick** [comment]
The `soe` branch was created to continue this work.

https://github.com/linkedin/goavro/tree/soe

**Comment by karrick** [comment]
Support should be provided in v2.9.0.
