### ISSUE TITLE
Question: Are fields required to be non-empty?

### ISSUE THREAD

**Issue by pkedy** [linkedin/goavro#110]
It would make sense that there should be at least one field defined in a type, but I have stumbled upon some Avro schemas in our Confluent Schema Registry that have types with no fields.  See `SomeRecord` in this example:

```json
{
    "type": "record",
    "name": "ExampleRecord",
    "namespace": "com.acme.messages",
    "fields": [
        {
            "name": "someProperty",
            "type": [
                "null",
                {
                    "type": "record",
                    "name": "SomeRecord",
                    "fields": []
                }
            ]
        }
    ]
}
```

While this does seem strange, this problematic schema (and possibly many others like it) are being used in production and our Java based producers/consumers are not rejecting it.  Unfortunately, `goavro` throws an error unless I change the following in `record.go`, `makeRecordCodec` (line 29).

```go
	if !ok || len(fieldSchemas) == 0 {
		return nil, fmt.Errorf("Record %q fields ought to be non-empty array: %v", c.typeName, fields)
	}
```
to

```go
	if !ok || fieldSchemas == nil {
		return nil, fmt.Errorf("Record %q fields ought to be non-nil array: %v", c.typeName, fields)
	}
```

The [Avro spec](https://avro.apache.org/docs/1.8.1/spec.html#schema_record) says:

> fields: a JSON array, listing fields (required). Each field is a JSON object with the following attributes:

Does "required" mean non-empty or non-null?  If this is allowed in Java, should this check be relaxed in `goavro`?

P.S. Thanks for developing this awesome library!!!

**Comment by karrick** [comment]
This is one of those unfortunate areas where the _Avro Specification_ seems ambiguous and many Avro implementations seem to error on the side of allowing things that do not make sense.

I truly am sorry for this issue. I suppose the library could be updated to reflect common usage among other libraries, even when that behavior goes against common sense usage.

**Comment by felixd** [comment]
Exactly same problem I am facing right now. Thanks for sollution @pkedy ;)

**Comment by karrick** [comment]
@felixd @pkedy Thanks for the dialog. I've merged in your changes. Sorry for the delay.

**Comment by maciek134** [comment]
> This is one of those unfortunate areas where the _Avro Specification_ seems ambiguous and many Avro implementations seem to error on the side of allowing things that do not make sense.

FYI while this might not make sense in Go, having records without fields is how you'd represent a tagged union's unit variant (enums in Rust or sealed Java abstract classes in recent Java allow that).
