### ISSUE TITLE
Default value of floats and doubles are cast into integers

### ISSUE THREAD

**Issue by Yopi** [linkedin/goavro#119]
I have an issue where I have a default value of a float (`0.0`) but that gets cast into `0` as the default value. This is no problem for `avro-tools` but Google's `bq` importer breaks due to it.

Example Schema:
```
{
    "type": "record",
    "name": "ExampleTable",
    "fields": [
        {"name": "doubletrouble, "type": "double", "default": 0.0}
    ]
}
```

Logged codec:
```
&{0xc4203461e0 {"fields":[{"default":0,"name":"doubletrouble","type":"double"}],"name":"ExampleTable","type":"record"} 0x147f2c0 0x147e9a0 0x147ef20 0x147f7d0}
```

**Comment by kdvy** [comment]
It looks like go-avro encodes correctly to 8 bytes for doubles see: https://github.com/linkedin/goavro/blob/master/floatingPoint_test.go#L21

What error are you getting from bq ?

**Comment by Yopi** [comment]
Sorry, should have included that error message as well:

```
Errors:
--
Error while reading data, error message: The Apache Avro  library failed to parse the header with the following error: Unexpected  type for default value: Expected 3, but found 2           (error code: invalid)
```

**Comment by kdvy** [comment]
Are you using the most recent version of the master branch ? When I try your sample schema it displays without the default in the canonical schema, and has both canonical and non-canonical schemas in it.  See below.

I was also able to decode the output OCF correctly using the reference avro 1.8.2 tools from: http://avro.apache.org/releases.html#20+May+2017%3A+Avro+1.8.2+Released

`&{0xc42000a320
{
    "type": "record",
    "name": "ExampleTable",
    "fields": [
        {"name": "doubletrouble", "type": "double", "default": 0.0}
    ]
}
 {"name":"ExampleTable","type":"record","fields":[{"name":"doubletrouble","type":"double"}]} 0x10ed4e0 0x10ecbc0 0x10ed140 0x10ed9f0}(ins)`

**Comment by Yopi** [comment]
Wow, now I feel stupid. I assumed I was running the latest version but that doesn't seem to be true. Upgrading to HEAD seems to have fixed the issue. Sorry for the false report 🙈, and thanks for the help!
