### ISSUE TITLE
go avro decode data

### ISSUE THREAD

**Issue by saviovincent** [linkedin/goavro#120]
Hi can someone please help with the issue:

https://stackoverflow.com/questions/51905167/goavro-not-able-to-validate-json-data-with-schema

Any help is much appreciated.

**Comment by karrick** [comment]
It appears that your JSON sample data is malformed. The Avro spec states that a JAON representation of a union must declare the which type the union takes on.

In your case, the type of the value is the name of the record.

Try this:

`{“field”:{“child”:{“field1”:”foo”,”field2”:”bar”}}}`

**Comment by karrick** [comment]
It might be helpful to manually create the data blob using Go native formats, then invoke the TextualFromNative method to see the output. That output adheres to the Avro specification, and it might help you see how to build your JSON blobs.

**Comment by karrick** [comment]
Also, please take a close look at the example on the README.md file. It shows how to convert from any of the supported formats to any of the other supported formats.

**Comment by karrick** [comment]
`package main

import (
	"fmt"

	"github.com/linkedin/goavro"
)

const schema = `{
  "namespace": "com.input",
  "name": "parent",
  "type": "record",
  "fields": [
    {
      "name": "field1",
      "type": [
        "null",
        {
          "type": "record",
          "name": "child",
          "fields": [
            {
              "name": "child1",
              "type": "string"
            },
            {
              "name": "child2",
              "type": "string"
            }
          ]
        }
      ]
    }
  ]
}
`

func main() {
	codec, err := goavro.NewCodec(schema)
	if err != nil {
		panic(err)
	}

	native := map[string]interface{}{
		"field1": map[string]interface{}{
			"com.input.child": map[string]interface{}{
				"child1": "foo",
				"child2": "bar",
			},
		},
	}

	textual, err := codec.TextualFromNative(nil, native)
	if err != nil {
		panic(err)
	}

	fmt.Println(string(textual))
	// Output: {"field1":{"com.input.child":{"child1":"foo","child2":"bar"}}}
}
`

**Comment by karrick** [comment]
There is a lot of extra verbosity in there, having to encode the type information into the JSON blob, but it is a necessary part of the Avro specification.

If your sample data matched the `textual` blob, then the decoder would be able to decode it correctly back into a Go native type.

**Comment by karrick** [comment]
Closing this ticket as I think I answered it about 6 months ago and there have been no replies since.
