### ISSUE TITLE
Codec's NativeFromTextual doesn't return a float32 value for a float value

### ISSUE THREAD

**Issue by elakito** [linkedin/goavro#128]
Codec NativeFromTextual is internally using strconv.ParseFloat and returning a float64 native value directly for a float typed data. This leads to an issue when the precision or comparison to the original float32 data is important.

This below PR fixes this issue.
https://github.com/linkedin/goavro/pull/127
please review. 
thanks

**Comment by karrick** [comment]
merged into v2.7.0, although I'm not sure why github did not automatically close this issue upon merge.
