### ISSUE TITLE
decimal field in a record may not be extracted

### ISSUE THREAD

**Issue by elakito** [linkedin/goavro#131]
When you have a decimal typed field in a record like defined here
`{"type": "record", "name": "myrecord", "fields" : [
	       {"name": "mydecimal", "type": "bytes", "logicalType": "decimal", "precision": 4, "scale": 2}]}`

Field mydecimal won't be extracted from a binary avro data with goavro.v2 v2.6.0 (note it works with v2.0.4).
The reason for this seems to be this line 
https://github.com/linkedin/goavro/blob/master/logical_type.go#L209
which replaces the name unconditionally. So, that will only work if the field name happens to be also "decimal".  I suppose the name should not be replaced if it is already set.

**Comment by karrick** [comment]
I'm sorry I have not been able to attend to this PR yet. I will take a look soon! Thanks for your help.
