### ISSUE TITLE
int and long should use the same decoder and encoder.

### ISSUE THREAD

**Issue by wuranbo** [linkedin/goavro#14]
rt

**Comment by karrick** [comment]
There is room for refactoring the common parts of the encoders and decoders for int, long, and similarly for float and double, and for bytes and string.

**Comment by flyinprogrammer** [comment]
mmm wut :expressionless: 

http://avro.apache.org/docs/1.7.6/spec.html#schema_primitive

seems to match:

https://github.com/linkedin/goavro/blob/master/codec.go#L248-L255

**Comment by wuranbo** [comment]
@karrick @flyinprogrammer my bad, I did not describe it clearly. 
I actually mean: 

The int and long type should have **same encoding method**. We should has two encoder, but with the almost same implement, for example: the int implement only limit the length of the input.

My evidence are:
1. http://avro.apache.org/docs/1.7.6/spec.html#binary_encode_primitive shows 

> int and long values are written using variable-length zig-zag coding. 
> value	hex
> 0	00
> -1	01
> 1	02
> -2	03
> 2	04
> ...
> -64	7f
> 64	 80 01
> 

2. http://lucene.apache.org/core/3_5_0/fileformats.html#VInt shows what is variable-length, the length(32 or 64)is variable specificed by the encoding method.

3. https://developers.google.com/protocol-buffers/docs/encoding?csw=1#signed-integers shows the what is zig-zag:  postive and negative are alternate showed.

So int and long follow the same encoding method and our implement now is not:  https://github.com/linkedin/goavro/blob/e7f48d7a02749290e2e01af20955c0a765989ac7/decoder.go#L105-L137

I first found it when I used goavro to decode an avro file.

Please reopen it, bro~
