### ISSUE TITLE
Latest release is not tagged on the most recent release

### ISSUE THREAD

**Issue by GeorgioCZY** [linkedin/goavro#143]
When using modules, `go get ./...` would fetch the latest release tag 2.20, which is not the most recent release in this repo.
My go.mod file shows `github.com/linkedin/goavro v2.1.0+incompatible` and caused all goavro tests to fail.
I need to manually change go.mod file to `github.com/linkedin/goavro v0.0.0-20181021212106-4a9979e6a077` to use the current master.

**Comment by karrick** [comment]
I have updated dependencies (and copyright notices along the way), and released a new tagged version 2.7.1 pointing at origin/master's HEAD. I hope this resolves this issue. Feel free to re-open if you re-experience this issue.

**Comment by karrick** [comment]
I think this one was fixed recently by a creative and insightful suggestion of another user.

I’m closing this issue, but please re-open if this still plagues you.
