### ISSUE TITLE
Releases after v2.1.0 are not usable via go modules

### ISSUE THREAD

**Issue by wfscheper** [linkedin/goavro#149]
I am unable to consume the latest versions of this library in a project that uses go modules.

I have created a test project that demonstrates this at [wfscheper/goavro-test](https://github.com/wfscheper/goavro-test).

The [current](https://github.com/wfscheper/goavro-test/tree/current) branch uses the example code from the README exactly. This branch will build, but will use the version tagged v2.1.0 (which was the last release before the go.mod file was added).

The [gopkg.in](https://github.com/wfscheper/goavro-test/tree/gopkg.in) branch uses the same code, but changes the import to use the suggested `gopkg.in/linkedin/goavro.v2` import path. This branch fails to build with
```shell
$ go build
go: downloading gopkg.in/linkedin/goavro.v2 v2.7.2
build github.com/wfscheper/goavro-test: cannot load gopkg.in/linkedin/goavro.v2: cannot find module providing package gopkg.in/linkedin/goavro.v2
```
The [master](https://github.com/wfscheper/goavro-test) branch uses the `replace` directive pointed a my fork that fixes the go.mod file and several internal imports.

**Comment by djchapm** [comment]
Me too.
Were you able to modify your go.mod to somehow use goavro ?

**Comment by wfscheper** [comment]
@djchapm Yes, that works but doesn't get you the latest version of goavro. For now, I'm using the master branch on my [fork](https://github.com/wfscheper/goavro) with the "replace" directive in go.mod. An example of this is [here](https://github.com/wfscheper/goavro-test).

**Comment by awillis** [comment]
I see that there is a `v1` branch, do we need a `v2` branch to resolve? As of right now, the installation documentation is invalid.

$ go get gopkg.in/linkedin/goavro.v2
go: gopkg.in/linkedin/goavro.v2@v2.7.2: go.mod has non-....v2 module path "github.com/linkedin/goavro" at revision v2.7.2

**Comment by wfscheper** [comment]
@awillis I do not believe that another branch is necessary. The go modules resolution requires that API breaking changes use a different import path. That is essentially what the gopkgs.in import path is doing, however the go.mod still declares that the module is `github.com/linkedin/goavro` when it should be `github.com/linkedin/goavro/v2`, which is why `go get` fails.

**Comment by domgreen** [comment]
Is there a workaround for this issue?
