### ISSUE TITLE
CRC32 checksums missing from Snappy encoding?

### ISSUE THREAD

**Issue by noahhl** [linkedin/goavro#15]
The Avro spec specifies that Snappy encoded file data blocks should contain a checksum after each block:
```
The "snappy" codec uses Google's Snappy compression library. Each compressed block is followed by the 4-byte, big-endian CRC32 checksum of the uncompressed data in the block.
```

As far as I can tell, that's not being added now ( `snappy.Encode` does not add a checksum, though the `Writer` interface of the library would). It works fine if you're both reading and writing using `goavro`, but breaks interoperability with other things using the Avro format that are expecting a checksum.

(it's possible I might just be missing the check-summing, and my difficulties with interoperability were elsewhere)

**Comment by karrick** [comment]
@noahhl,

Thanks for the heads up on the issue. This will be addressed when I get some cycles. I really appreciate this information!
