### ISSUE TITLE
Please stop using gopkg.in

### ISSUE THREAD

**Issue by y0ssar1an** [linkedin/goavro#153]
This is an old and obsolete method of locking versions of Go code. It was a fine solution before we had `Gopkg.lock` and `go.mod`, but now it just creates headaches for people trying to use your library. Things would be a lot simpler if you just used the `github.com` URL for your import path. Thanks!

**Comment by smyrman** [comment]
I am getting:

```
$ go get gopkg.in/linkedin/goavro.v2
go: gopkg.in/linkedin/goavro.v2@v2.7.2: go.mod has non-....v2 module path "github.com/linkedin/goavro" at revision v2.7.2
go: error loading module requirements
```

With go version:
```
$ go version                                                                                                         :(
go version go1.12.4 darwin/amd64
```
