### ISSUE TITLE
AVDL-based codegen

### ISSUE THREAD

**Issue by virtuald** [linkedin/goavro#16]
We just recently open sourced our [fork of the AVRO java code generator](https://github.com/BBN-D/avro-golang-compiler), which generates golang avro objects from avdl files. It currently generates bindings and associated roundtrip unit tests that use the AVRO C libraries for serialization/deserialization, as at the time it was written last summer we were not aware of any golang avro implementations.

Unfortunately, we no longer use golang in our environment, so we aren't planning on updating the code generator. However, with a little work, I suspect either this project or the other golang avro project could adapt it to use golang bindings instead of the C library.

**Comment by virtuald** [comment]
Also posted at https://github.com/stealthly/go-avro/issues/38

**Comment by karrick** [comment]
Thanks for the reference. There has been some discussion about generating go code on the fly based on a particular schema. This looks very interesting.
