### ISSUE TITLE
Handle wider range for logical type time conversion

### ISSUE THREAD

**Issue by smyrman** [linkedin/goavro#160]
I noticed that the impplementation of `timeStampMicrosFromNative` is written in a way, so that it will actually not handle as wide a time-range as it could. In particular it won't correctly be able to handle the Windows zero-time (January 1601 00:00:00 UTC) due to int64 overflow.

https://github.com/linkedin/goavro/blob/562b52dbff0d1cca080380a7ec5035f28dd6bdf4/logical_type.go#L163

## Solution

This are the implementations we have ourselves in an internal `timeconv` package:

```go
package timeconv

import "time"

// UnixMicro returns the number of microseconds since the epoch (Jan 1 1970
// UTC) for the passed in Time.
//
// The conversation is written to handle the maximum range allowed by the int64
// value, which includes the Windows NT zero-time (Jan 1, 1601 UTC).
func UnixMicro(t time.Time) int64 {
	usec := t.UTC().Unix() * 1e6
	usec += int64(t.Nanosecond() / 1e3)
	return usec
}

// FromUnixMicro takes the number of microseconds since the epoch (Jan 1 1970
// UTC), and converts it to a Go UTC time.
//
// The conversation is written to handle the maximum range allowed by the int64
// value, which includes the Windows NT zero-time (Jan 1, 1601 UTC).
func FromUnixMicro(us int64) time.Time {
	sec := (us / 1e6)
	nsec := (us - (sec * 1e6)) * 1e3
	return time.Unix(sec, nsec).UTC()
}

```

This handles the seconds and nanosecond parts separately, so that it doesn't suffer from overflow, and can handle the full time-range described by `int64`.

We don't have a similar implementation for milliseconds, but it should be straight forward enough to copy and adapt.

**Comment by karrick** [comment]
Wow, I did not know that Windows had an "epoch" back in 1601. :D

**Comment by smyrman** [comment]
Thanks 👍
