### ISSUE TITLE
Serialize and Deserialize Avro Data without Known Schema 

### ISSUE THREAD

**Issue by jon-whit** [linkedin/goavro#164]
One of the benefits of using Apache Avro is that data in Avro is always stored with its corresponding schema, meaning we can always read a serialized item regardless of whether we know the schema ahead of time.

Most of the examples I'm seeing, and from reading the Godoc, it appears that this library is largely based around knowing the Avro schema ahead of time for a datum. Do you have plans on supporting, or existing support for decoding Avro data without knowing the schema?

**Comment by karrick** [comment]
There are two parts to this library, basic encoding and second of Avro data, and using the OCF file format for encoding and decoding Avro data.

While several of the examples do show the basic encoding and decoding of Avro data, there are a few examples of using OCF support in the library to work with Avro files.

https://github.com/linkedin/goavro/tree/master/examples/ab2t

https://github.com/linkedin/goavro/tree/master/examples/arw

https://github.com/linkedin/goavro/tree/master/examples/avroheader

https://github.com/linkedin/goavro/tree/master/examples/splice

I hope you find these example informative.

**Comment by jon-whit** [comment]
Ah, thank you! I will take a look.
