### ISSUE TITLE
get record from ocf as []byte

### ISSUE THREAD

**Issue by kmulvey** [linkedin/goavro#168]
is there a way to get a record from Read() just as the bytes and not the datastructure defined by the schema? I would like to just use goavro to do the record splitting for me.

**Comment by karrick** [comment]
I don’t have enough information to answer this question.

What format are you reading data from? What format are you trying to get the data into?

**Comment by karrick** [comment]
Looks like this might be related to #108.

**Comment by kmulvey** [comment]
yes, exactly that, thanks
