### ISSUE TITLE
NativeFromBinary should honor codec versus interpretation

### ISSUE THREAD

**Issue by durango** [linkedin/goavro#170]
Given the following codec:

```json
{
		"type": "record",
		"name": "version",
		"namespace": "versions",
		"fields": [
			{
				"name": "ts",
				"type": "long"
			},
			{
				"name": "version",
				"type": "int"
			},
			{
				"name": "version_hex",
				"type": "string"
			}
		]
	}
```

When using the NativeFromBinary function with this codec I get the following error:

`cannot decode binary record "versions.version" field "version_hex": cannot decode binary string: cannot decode binary bytes: negative size: -54`

When I `avro-tojson` here's my output:
```json
{"ts":1233046715,"version":1,"version_hex":"0x00000001"}
```
As you can see, `version_hex` is a string in all reality. But the function *thinks* it is a binary. The codec itself should be honored and *not* what it *thinks* to be true.

**Comment by karrick** [comment]
Could you please add the sequence of binary bytes used to get the above error?

**Comment by durango** [comment]
@karrick I'm not really sure on what you're asking for. There should be no bytes within this equation. Just strings, ints, and longs.

**Comment by karrick** [comment]
Here's some code to work with:

```Go
// #170
//
// This code illustrates using the schema from issue #170, and converting a
// textual (JSON) value to native format, then to binary format, and back to
// native format again.

package main

import (
	"fmt"

	"github.com/linkedin/goavro"
)

const schema = `
{
  "type": "record",
  "name": "version",
  "namespace": "versions",
  "fields": [
    {
      "name": "ts",
      "type": "long"
    },
    {
      "name": "version",
      "type": "int"
    },
    {
      "name": "version_hex",
      "type": "string"
    }
  ]
}
`

func main() {
	// First let us create a codec from the provided schema.  For this
	// non-production program, we'll handle errors with a panic.
	codec, err := goavro.NewCodec(schema)
	if err != nil {
		panic(err)
	}

	// We will start with a text version of the record provided in the issue,
	// because that is a valid Avro text encoding of a record.
	someText := `{"ts":1233046715,"version":1,"version_hex":"0x00000001"}`

	// Convert the Avro text version of the record to native Go data types and
	// print it.  Note that records are converted to maps with keys of string
	// and values of empty interface.
	someNative, _, err := codec.NativeFromTextual([]byte(someText))
	if err != nil {
		panic(err)
	}
	fmt.Println(someNative)

	// Once we have data in Go native representation, we can then convert the
	// data to Avro binary representation and print it.
	someBinary, err := codec.BinaryFromNative(nil, someNative)
	if err != nil {
		panic(err)
	}
	fmt.Println(someBinary)

	// Here's where the user is reporting a bug in the issue, but it's not
	// happening here.  I strongly suspect the binary input to NativeFromBinary
	// is not a correct Avro binary representation of the provided schema.
	moreNative, _, err := codec.NativeFromBinary(someBinary)
	if err != nil {
		panic(err)
	}
	fmt.Println(moreNative)

	// For completeness, let us also convert the Go native representation that
	// we just decoded to text again and print that.  It should be equivalent to
	// the original text input.
	moreText, err := codec.TextualFromNative(nil, moreNative)
	if err != nil {
		panic(err)
	}
	fmt.Println(string(moreText))
}
```

```Bash
go run main.go 
map[ts:1233046715 version:1 version_hex:0x00000001]
[246 178 246 151 9 2 20 48 120 48 48 48 48 48 48 48 49]
map[ts:1233046715 version:1 version_hex:0x00000001]
{"version":1,"version_hex":"0x00000001","ts":1233046715}
```

**Comment by karrick** [comment]
The binary bytes I was referring to in my original question is essentially the slice of bytes printed in the output above, namely `[246 178 246 151 9 2 20 48 120 48 48 48 48 48 48 48 49]`.

The error message that you pasted into the issue is pasted here again for reference:

```
cannot decode binary record "versions.version" field "version_hex": cannot decode binary string: cannot decode binary bytes: negative size: -54
```

What this means is that when decoding the binary string, the `version_hex` field of the record, it read an integer from the stream of bytes and found a negative number, namely -54, where it expected to read the size of the string. In the binary slice I pasted above, the size is encoded as 20, which in variable length zig-zag encoding, represents 10, and the string `0x00000001` is exactly 10 bytes long. So `goavro` encoded the length, 10 bytes, as 20 because 10 is encoded as 20 in variable length zig-zag encoding, and then after the length another 10 bytes in the byte slice represent the 10 bytes from the string.

**Comment by karrick** [comment]
I left a comment in the code example above immediately prior to the call to `NativeFromBinary` suggesting that I strongly believe the problem you are having is because the bytes being fed into the binary Avro decoder was not properly encoded using the provided schema. I might be wrong, but until I would have more information to rule that out.

**Comment by karrick** [comment]
Also, I am not familiar with the `avro-tojson` tool you mentioned above, nor did I read what format the original data is in. Is it from an OCF file? Was the data encoded using Single-Object Encoding?

Please see my comments from #165 about various binary Avro encodings, and how they have tripped people up from time to time.

**Comment by durango** [comment]
So I'm creating a new file with the snappy compression like so:

```go
type AvroWriter struct {
	fh io.WriteCloser
	w  *goavro.OCFWriter
}

func (a *AvroFile) Writer() (*AvroWriter, error) {
	f, err := os.OpenFile(a.filename, os.O_CREATE|os.O_APPEND|os.O_RDWR, 0700)
	if err != nil {
		return nil, errors.Wrapf(err, "Could not create file: %s", a.filename)
	}

	config := goavro.OCFConfig{
		W:               f,
		Codec:           a.codec,
		CompressionName: goavro.CompressionSnappyLabel,
	}

	w, err := goavro.NewOCFWriter(config)
	if err != nil {
		return nil, errors.Wrap(err, "could not start OCF writer")
	}

	return &AvroWriter{
		fh: f,
		w:  w,
	}, nil
}

func (a *AvroWriter) Append(item AvroMarshaller) error {
	return a.w.Append(item.MarshalAvro())
}

func (a *AvroWriter) Close() error {
	return a.fh.Close()
}
```

later on im writing...

```go
writer, err := out.Writer()
if err != nil {
    t.errs <- errors.Wrap(err, "could not start writer")
    return
}

err = writer.Append(versionStruct)
if err != nil {
    t.errs <- errors.Wrap(err, "could not append")
    return
}
```

Everything saves fine, hive reads the file normally/correctly. `avro-tojson` is an official avro tool that dumps the input file into a json format (as previously shown). 

When I manually read from the file from OCFReader I can marshal it into the way I want but that's a super hacky method:

```go
// decode our blocks
ocfr, err := goavro.NewOCFReader(bytes.NewBuffer(avroFileBytes))
if err != nil {
    t.errs <- errors.Wrapf(err, "failed to read from buffer")
    continue
}

for ocfr.Scan() {
    datum, _ := ocfr.Read()
    b := &codecs.Versions{}
// this is what I have to do in order to get everything to work
    b.MapFromAvro(datum.(map[string]interface{}))
}
```

**Comment by durango** [comment]
Also, I am using the same exact schema (or goavro.Codec) to read/write from the file

**Comment by karrick** [comment]
Interesting. Can you post the code you’re using to write that file?

**Comment by durango** [comment]
that is it...

```go
writer, err := out.Writer()
if err != nil {
    t.errs <- errors.Wrap(err, "could not start writer")
    return
}

err = writer.Append(versionStruct)
if err != nil {
    t.errs <- errors.Wrap(err, "could not append")
    return
}
```

you're just missing the struct

```go
type vs struct {
ts int64
version int32
versionHex string
}

func (v vs) MarshalAvro() []interface{} {
	o := map[string]interface{}{
		"ts":            v.ts,
		"version":       v.version,
		"version_hex":   "0x" + v.versionHex,
	}

	return []interface{}{o}
}

versionStruct := &vs{1233046715,1,"0x00000001"}
```

**Comment by karrick** [comment]
Okay. I think I found the problem. It’s where the above code calls the Append method on the OCFWriter, but rather than sending it the item, it’s calling Append with the return value of a MarshalAvro method.

OCFWriter’s Append takes the actual native datum rather than a byte slice.

**Comment by durango** [comment]
So the `writer` isn't the issue, it's the `reader`

**Comment by karrick** [comment]
Quite the opposite. The problem is in the writing code you pasted above. It is converting the datum to Avro binary, then feeding that binary slice of bytes to OCFWriter’s Append function which also converts it into binary.
