### ISSUE TITLE
goavro fails when namespace is an empty string

### ISSUE THREAD

**Issue by ian-markowitz** [linkedin/goavro#177]
I am getting the following error
`cannot read OCF header with invalid avro.schema: Record "field_name" field 6 ought to be valid Avro named type: Record ought to have valid name: schema namespace, if provided, ought to be non-empty string; received: string`

When trying to read an Avro file.
The issue appears to be a type which has `"namespace": ""`

The Avro spec http://avro.apache.org/docs/1.8.1/spec.html#names
Says that "The empty string may also be used as a namespace to indicate the null namespace"

**Comment by karrick** [comment]
Thanks for opening this issue and for linking the spec line. Are you able to either paste a copy of the Avro schema you're working with, or a redacted or simplified version of the same?

**Comment by karrick** [comment]
bug resolved in v2.9.7.

thanks for reporting
