### ISSUE TITLE
Working example of creation a Avro Decimal datatype with gogen-avro ?

### ISSUE THREAD

**Issue by divo77** [linkedin/goavro#180]
HI, It would be super cool if you give some examples of working properly for serialization/deserialization the Logical data types with gogen avro structs. I am in stack with the situation where I need to read the bytes from Avro Native like:

var codecDecimal, err= goavro.NewCodec(`{"type": ["null", {"type": "bytes", "logicalType": "decimal", "precision": 6, "scale": 4}]}`)
bytesDecimalBinary, err := codecDecimal.BinaryFromNative(nil, map[string]interface{}{"bytes.decimal": big.NewRat(500,4)})

from the Native GoAvro form I can  read the value as big.Rat 

What need to be done to assign the value to gogen avro struct correctly to produce the correct Decimal number after serialization to binary form ?

type AvroLogical struct {
	TEST__DECIMAL *UnionNullBytes
}

in my case 

		gogenAvro:= model.NewAvroLogical()
		gogenAvro.TEST_DECIMAL=model.NewUnionNullBytes()
		gogenAvro.TEST_DECIMAL.Bytes = **NEW_DECIMAL**
		gogenAvro.TEST_DECIMAL.UnionType = model.UnionNullBytesTypeEnumBytes

SO how to make a correct **NEW_DECIMAL** in my code ?

**Comment by karrick** [comment]
I am not sure what this question is asking, but it seems like you are curious how a person can convert data from the format used by goavro to a different library?

If so, my first instinct is to use Avro as the data translation mechanism. Both libraries claim to convert to and from Avro binary data. If true, one can serialize some data using one of the libraries into binary Avro, then deserialize it using the other library into whichever format that library wants.

**Comment by karrick** [comment]
Maybe I misread your question, but it would help me to understand what source data you have and what target format you need that data to be represented in.

Once that is understood, there are an infinite number of ways to convert from source to target, but only a few methods will be obvious, and a smaller few performant.
