### ISSUE TITLE
Message Framing

### ISSUE THREAD

**Issue by pm-kartik-sura** [linkedin/goavro#2]
Hi Team,

The usecase is: I want to send multiple avro objects in an  HTTP call. 

Typically I want to bundle say 10 objects, compress them using snappy or gzip and send it over.

Is there any feature directly in goavro, or would I  have to implement a ghetto-message-framing myself?

**Comment by karrick** [comment]
I am actually done with half of the message framing already. I have the write side working with a nice API. I'm building the read side of the feature now.

**Comment by karrick** [comment]
Please take a look at examples/net/server.go and examples/net/client.go for an example of framing Avro data across a network connection.

Both Null and Deflate compression are working, but I need to fix a bug with Snappy compression.

**Comment by karrick** [comment]
Goavro now has google snappy support.

When using the goavro.Reader type, it detects the compression codec in the metadata, and uses the appropriate decompressor to decompress the data.

When using the goavro.Writer type, the goavro.Compression() method can be used to change from the default of null compression to either Deflate or Snappy.

See the updated README.md and the programs inexamples/file/ for more examples.
