### ISSUE TITLE
Lack of schema static compiler

### ISSUE THREAD

**Issue by hhkbp2** [linkedin/goavro#22]
Hi,

Is there any requirement or development plan for static compiler of avro schema? currently fields of record are accessed by type interface{}. Programmers need to remember its real type and do casting all around, which is somewhat  cumbersome. If schema compiler is available, all record structs with schema-specified type should be decoded to be used, which would fix this problem.

**Comment by karrick** [comment]
There has been talk about creating a static compiler for complex record types. I haven't been able to find the time to look into it yet.

**Comment by tristanz** [comment]
Not sure how much code could be reused but there is a codegenerator here: https://github.com/stealthly/go-avro/tree/master/codegen

I agree this would be really nice.

**Comment by alanctgardner** [comment]
I started work on a code generator here: github.com/alanctgardner/gogen-avro

It supports generating structs and encoding them as Avro right now - decoding is coming soon. PRs and issues are welcome!

**Comment by cweaver1321** [comment]
Hi,

The project I am working on currently needs a go parser for dynamically converting a avro schema file, in json, to be used in for serializing json data in flight. This is not possible with the current goavro implementation as we have nested records. I will be investigating the gogen-avro and the codegen options but if someone finds a better one please update this issue or let me know.

Thank you

**Comment by karrick** [comment]
I am closing this issue, because while it would be great to have a static Avro schema compiler, it's not within the scope of this project, and there are alternatives, such as mentioned above by @alanctgardner.

**Comment by karrick** [comment]
@cweaver1321, I have updated this library to have full JSON Avro support.
