### ISSUE TITLE
BufferFromReader breaks for schema > 4kB

### ISSUE THREAD

**Issue by sgn1** [linkedin/goavro#23]
Hi, 

I ran into an issue while reading avro datum from avro ocf. File is written using goavro. Issue disappears when - schema size < 4KB or if I do not use BufferFromReader.
Error msg is - cannot build cannot read header metadata: cannot decode bytes: buffer underrun.

When I looked into the code - issue is in decoder.go while reading schema bytes - 
the line below reads less bytes than expected.
bytesRead, err := r.Read(buf).

IMO, writer is writing data correctly. 
Also issue can be reproduced by using the file example given on github. We need to make schema longer by changing "doc" entry to > 4kB.

Thanks.

**Comment by karrick** [comment]
Thanks for this bug find!
