### ISSUE TITLE
Error when encoding a union type in schema with namespace field

### ISSUE THREAD

**Issue by MikkelWestermann** [linkedin/goavro#233]
I'm using goavro for encoding/decoding avro schemas for communication using kafka. But I've encountered a problem where encoding data in a schema that has a union value (null or enum), I get the following error:
```
cannot decode textual record "com.foo.bar.FooBar": cannot decode textual union: cannot decode textual map: cannot determine codec: "FooBarEvent" for key: "event"
```

I've followed the examples outlined in https://github.com/linkedin/goavro/issues/121, which produced JSON with a similar structure to the one in the example, but it still didn't work. I tried making a simple example (just a main.go file) to see if I could figure out what was wrong. From this example I descovered that removing the ```namespace``` field (or setting it to an empty string) resolved the error and the data was encoded correctly, but I would prefer not having to delete the namespace from my schema. 

Below follows the above mentioned "simple example":
```go
package main

import (
	"encoding/json"
	"fmt"

	goavro "github.com/linkedin/goavro/v2"
)

func main() {
	const avroSchema = `
	{
		"type": "record",
		"name": "FooBar",
		"namespace": "com.foo.bar",
		"fields": [
		  {
				"name": "event",
				"type": [
					"null",
					{
						"type": "enum",
						"name": "FooBarEvent",
						"symbols": ["CREATED", "UPDATED"]
					}
				]
			}
		]
	}
	`
	codec, _ := goavro.NewCodec(avroSchema)

	const avroJson = `{"event":{"FooBarEvent":"CREATED"}}`

	native, _, err := codec.NativeFromTextual([]byte(avroJson))
	if err != nil {
		panic(err)
	}

	blob, err := json.Marshal(native)
	if err != nil {
		panic(err)
	}
	fmt.Println(string(blob))
}
```
The main function in this example prints the following: 
```
panic: cannot decode textual record "com.foo.bar.FooBar": cannot decode textual union: cannot decode textual map: cannot determine codec: "FooBarEvent" for key: "event"
```

But if I remove the namespace field (entire example provided for clearity):

```go
package main

import (
	"encoding/json"
	"fmt"

	goavro "github.com/linkedin/goavro/v2"
)

func main() {
	const avroSchema = `
	{
		"type": "record",
		"name": "FooBar",
		"fields": [
		  {
				"name": "event",
				"type": [
					"null",
					{
						"type": "enum",
						"name": "FooBarEvent",
						"symbols": ["CREATED", "UPDATED"]
					}
				]
			}
		]
	}
	`
	codec, _ := goavro.NewCodec(avroSchema)

	const avroJson = `{"event":{"FooBarEvent":"CREATED"}}`

	native, _, err := codec.NativeFromTextual([]byte(avroJson))
	if err != nil {
		panic(err)
	}

	blob, err := json.Marshal(native)
	if err != nil {
		panic(err)
	}
	fmt.Println(string(blob))
}
```

Now the main function prints:
```
{"event":{"FooBarEvent":"CREATED"}}
```

So, my question is whether or not goavro prevents me from using the ```namespace``` field in my schema in any way? Some clearity surrounding this would be appreciated, as I cannot figure out why the namespace would be a problem in this case. I've looked at the avro spec and it seems like the ```enum``` type can have a ```namespace``` field as well, but it does not appear to make a difference, regardless of what I set this to.

**Comment by xmcqueen** [comment]
The schemas are supposed to support namespaces, and in general they do.   This test case passes:

```
	testTextCodecPass(t, `{"type":"record","name":"kubeEvents","namespace":"com.foo.bar.FooBar","fields":[{"name":"field1","type":["string","null"],"default":""}]}`, map[string]interface{}{"field1": nil}, []byte(`{"field1":null}`))

```
I can duplicate your error it with this test case:

```
testTextCodecPass(t, `{"type":"record","name":"FooBar","namespace":"com.foo.bar","fields":[{"name":"event","type":["null",{"type":"enum","name":"FooBarEvent","symbols":["CREATED","UPDATED"]}]}]}`, map[string]interface{}{"event": map[string]interface{}{"FooBarEvent": "CREATED"}}, []byte(`{"event":{"FooBarEvent":"CREATED"}}`))
```

Take away the namespace and it passes:

```
testTextCodecPass(t, `{"type":"record","name":"FooBar","fields":[{"name":"event","type":["null",{"type":"enum","name":"FooBarEvent","symbols":["CREATED","UPDATED"]}]}]}`, map[string]interface{}{"event": map[string]interface{}{"FooBarEvent": "CREATED"}}, []byte(`{"event":{"FooBarEvent":"CREATED"}}`))

```

It must be specific to the enum type.

I'll check it out.

**Comment by xmcqueen** [comment]
@MikkelWestermann if you change the input json to the following (specifying the namespace on the event), your example code will work:

```
{"event":{"com.foo.bar.FooBarEvent":"CREATED"}}
```

I think we need the opinion of the maintainer on this.  I'll think about it more too.

Here's a testcase:

```
testTextCodecPass(t, `{"type":"record","name":"FooBar","namespace":"com.foo.bar","fields":[{"name":"event","type":["null",{"type":"enum","name":"FooBarEvent","symbols":["CREATED","UPDATED"]}]}]}`, map[string]interface{}{"event": Union("com.foo.bar.FooBarEvent", "CREATED")}, []byte(`{"event":{"com.foo.bar.FooBarEvent":"CREATED"}}`))

```

**Comment by MikkelWestermann** [comment]
Ahh I see, so I just need to use the namespace in the name. That works - thank you!
