### ISSUE TITLE
Structs copy when calling method

### ISSUE THREAD

**Issue by hhkbp2** [linkedin/goavro#24]
Hi,

There are many places in the source code, methods of some structs(record, codec, etc) are defined without pointer, e.g.

``` go
func (r Record) Get(fieldName string) (interface{}, error) {
```

(record.go, line 44)

And these structs will be copied everytime calling these methods. Please refer to this example for this behaviour of Golang, which copies value when calling method. 

[http://play.golang.org/p/_UVasafGHc](http://play.golang.org/p/_UVasafGHc)

I think on most "read only without modification" methods, passing pointer is good enough to avoid the cost of value copy for the whole struct.

**Comment by karrick** [comment]
I agree with you and think it would be a performance improvement to pass by reference rather than value.

**Comment by karrick** [comment]
You raise an excellent point. I'm closing as "Won't Fix" however, because the new version of the library ensures methods are called by pointers to the structures themselves.
