### ISSUE TITLE
Failing to decode a schema with a nullable array of strings

### ISSUE THREAD

**Issue by dlahyani** [linkedin/goavro#255]
This is the schema:
```json
{
  "doc": "Event with array of strings",
  "name": "my_event",
  "namespace": "events",
  "type": "record",
  "fields": [
	{
	  "default": null,
	  "doc": "A nullable list of requirements, null or empty array means no special requirements",
	  "name": "requirements",
	  "type": [
		"null",
		{
		  "items": "string", 
		  "type": "array"
		}
	  ]
	}
  ]
}
```

This is the struct:
```go
type MyEvent struct {
	Requirements []string `avro:"requirements"`
}
```

Maybe I am missing something but AFAIU this should work and properly encode `MyEvent` instance using the given schema, however this fails with an error saying: *Requirements: avro: unable to resolve type []string*

This is the code that tries to encode an object of type `MyEvent` using the schema above:
```go
// schema is loaded using avro.Parse on the schema above.
e := MyEvent{Requirements: []string{"foo", "bar"}}
buf, err = avro.Marshal(schema, e)
```

Here's a Go playground allowing to easily reproduce the error:
https://go.dev/play/p/pOcqvLA9tvw

**Comment by xmcqueen** [comment]
Thanks, yes I'm pretty sure this is against the wrong repo.  I have checked the provided schema and it compiles here.  This library [encodes records into go maps](https://github.com/linkedin/goavro#getting-data-into-and-out-of-records).  Here are some [examples](https://github.com/linkedin/goavro/blob/master/record_test.go#L555).

@dlahyani reopen as-needed

thanks

**Comment by dlahyani** [comment]
Thanks @mihaitodor and @xmcqueen , this is indeed the wrong repo, sorry for the hustle.
Anyway good to hear it works as expected with `goavro` , maybe we will switch :)
