### ISSUE TITLE
Retrieving information about the schema after decoding

### ISSUE THREAD

**Issue by dgunay** [linkedin/goavro#259]
I am working with the [Salesforce Pub/Sub API](https://developer.salesforce.com/docs/platform/pub-sub-api/overview). It encodes some information about the payloads [as a bitmap](https://developer.salesforce.com/docs/platform/pub-sub-api/guide/event-deserialization-considerations.html) (1 bit = the field at this position changed). In order to make use of this information, I need to know the names of the fields in the Avro schema at runtime.

It looks like when `Codec` is constructed, the parsed Avro schema is thrown out. Does this mean I have to `json.Unmarshal` the schema from JSON again every time I want to do this, or is there a better way (besides caching the schema myself somewhere else)?

**Comment by xmcqueen** [comment]
You are thinking that as you parse the avro-encoded payload, you will be checking the corresponding field name, looking for the bitmap field?  There's no tool in here to step through a payload like that.  

You can get the entire schema from the codec using  [CanonicalSchema](https://github.com/linkedin/goavro/blob/master/codec.go#L593), but I don't know if that helps.

**Comment by xmcqueen** [comment]
Somebody pointed this out.  Its nameFromIndex, but at this time its not well exposed.  Putting it here for the record:

https://github.com/linkedin/goavro/blob/48fab015eec7832f6a6943a934dfa04ae2a9ee46/record.go#L131

**Comment by xmcqueen** [comment]
no response, closing
