### ISSUE TITLE
Parsing fails with union types

### ISSUE THREAD

**Issue by kapjoshi-cisco** [linkedin/goavro#262]
My code :
```bash
func ExampleNativeFromTextual() {
	codec, err := goavro.NewCodec(`{
			  "name": "com.MyAccount",
			  "type": "record",
			  "fields": [
				{"name": "topLevelDomain", "type": [ "null", "string"], "default": null}
			  ]
			}`)
	if err != nil {
		fmt.Println(err)
	}
	text := []byte(`{"topLevelDomain": "gmail.com"}`)
	native, _, err := codec.NativeFromTextual(text)
	if err != nil {
		fmt.Println("error", err)
	}

	fmt.Printf("%v native is", native)
}
```
Error:
```
error cannot decode textual record "com.MyAccount": cannot decode textual union: expected: '{'; actual: '"'
<nil> native is
```
Can someone please help me in getting this issue resolved. Expectation is to parse this avro data through the schema. Please feel free to point out any mistakes made.

**Comment by kapjoshi-cisco** [comment]
@karrick ?

**Comment by xmcqueen** [comment]
I'm looking into this.  In general the union types are working, but I too see your example as failing and I don't know why yet.

**Comment by xmcqueen** [comment]
OK I see what's going on here.  You are shooting regular json in and expecting it is matched by the avro schema.  It you look at the spec [here](https://avro.apache.org/docs/1.11.1/specification/_print/#json-encoding), you will see that json that corresponds a union type is expected to be specially annotated to indicate the branch of the union.  See below for a way forward.  This small patch to your example works, and it shows how the json managed per the avro spec, handles unions in an unexpected way:

```
func ExampleNativeFromTextual() {
        codec, err := NewCodec(`{ "name": "com.MyAccount", "type": "record", "fields": [ {"name": "topLevelDomain", "type": [ "null", "string"], "default": null} ] }`)
        if err != nil {
                fmt.Println(err)
        }
        text := []byte(`{"topLevelDomain": {"string":"gmail.com"}}`)
        native, _, err := codec.NativeFromTextual(text)
        if err != nil {
                fmt.Println("error", err)
        }

        fmt.Printf("%v", native)
        // Output: map[topLevelDomain:map[string:gmail.com]]
}
```

This library has a way to intake regular json.  Here's the corresponding example:

https://github.com/linkedin/goavro/blob/master/union_test.go#L266

There are many examples, showing the avro and the plain text json, in the unit tests in here:

https://github.com/linkedin/goavro/blob/master/union_test.go#L299

**Comment by xmcqueen** [comment]
Please reopen this if you have any more questions on this.  Sorry for the slow response.
