### ISSUE TITLE
Reading a avro file and decode the go native types

### ISSUE THREAD

**Issue by kapjoshi-cisco** [linkedin/goavro#263]
@karrick can you please help me with any links or example where they are reading from avro file and then parsing it to Go native types, using either codec.NativeFromTextual or codec.NativeFromBinary APIs. Im struggling a bit for this.

**Comment by mihaitodor** [comment]
Both `NativeFromTextual` and `NativeFromBinary` produce a "native" object that I think is only meant to be used by the Goavro APIs. What you can do is to then call `TextualFromNative` to obtain a JSON string representation and then use `json.Unmarshal` to decode that into a Go structure. Alternatively, I can imagine using something like [mapstructure](https://github.com/mitchellh/mapstructure) to extract what you need from the "native" object, but I'm not sure if that's such a good idea...

**Comment by xmcqueen** [comment]
There's a tool in the repo (examples/roundtrip), which is used for local iteration on avro schemas, and it does an encode->decode.  Maybe that will be of some use for you as an example of taking an avro binary object and pulling it into go structs:

[roundtrip tool](https://github.com/linkedin/goavro/blob/master/examples/roundtrip/main.go#L151)
