### ISSUE TITLE
Error while ignoring field

### ISSUE THREAD

**Issue by pm-kartik-sura** [linkedin/goavro#3]
When I set an int field with a default value and chose to ignore it i get the following error:
      {
            "name": "ID",
            "type": "int",
   	     "doc" : "ID of the system",
	     "default": 0

        }

 cannot encode int: expected: int32; actual: float64

**Comment by karrick** [comment]
Can you give me a code snippet? The error message says a float64 is being passed to the encoder.

**Comment by karrick** [comment]
I figured out why this is a problem. The encoder struggles when the default value is null due to a bug in how it uses reflection to see if a default value was set.

**Comment by karrick** [comment]
Please update your version of goavro as the fix required a code change.

```bash
go get -u github.com/linkedin/goavro
```
