### ISSUE TITLE
NewRecord panics when receiving an invalid schema instead of returning error

### ISSUE THREAD

**Issue by rweics** [linkedin/goavro#45]
```
goroutine 6 [running]:
panic(0x476820, 0xc82000a0f0)
    /usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:464 +0x3e6
testing.tRunner.func1(0xc82019c870)
    /usr/local/Cellar/go/1.6/libexec/src/testing/testing.go:467 +0x192
panic(0x476820, 0xc82000a0f0)
    /usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:426 +0x4e9
github.com/linkedin/goavro.NewRecord(0xc8200519f8, 0x1, 0x1, 0xc8203a79e0, 0x0, 0x0)
    $GOPATH/src/github.com/linkedin/goavro/record.go:148 +0x11a
```

**Comment by karrick** [comment]
are you legally able to share a copy of that schema so I can see what's going on? I understand if you're not able to because of work restrictions...

**Comment by karrick** [comment]
The newer version of this library no longer uses NewRecord to create record instances, but rather uses simple Go maps. Send a Go map instance with keys that match the record's fields to the encoder and it will return an encoded record. Decoding a record will return a Go map with keys that match the record fields.

https://github.com/karrick/goavro
