### ISSUE TITLE
Fail to encode missing integer field when default value is also an integer

### ISSUE THREAD

**Issue by rweics** [linkedin/goavro#46]
Error message:
`cannot encode union (union): datum ought match schema: expected: int32, null; received: float64"`
Schema of the field:
```
{
	"default": 123,
	"name": "testField",
	"type": [
		"int",
		"null"
	]
}
```

**Comment by karrick** [comment]
@rweics,

I'm added a few test cases to make sure with the other recent bug fixes that this issue is also resolved.

**Comment by rweics** [comment]
Thanks @karrick for taking care of this!
