### ISSUE TITLE
longdecoder overflow / dropping most significant bit if value > int64

### ISSUE THREAD

**Issue by cetex** [linkedin/goavro#49]
Hi!

I have an issue, somehow it seems like the longdecoder is dropping the most significant bit.
https://github.com/linkedin/goavro/blob/master/decoder.go#L122-L137

The data we store in avro as a binary representation from another library:
binary: 1011001101111100010000101000010111000111000011000000100000110000
as uint64: 12933285372238759984
as int64: -5513458701470791632

But somehow i get this value when reading it:
int64: 3709913335383984176
Tried casting it to uint64: 3709913335383984176
This is equivalent to dropping the first / left-most / most significant bit of the data.

if we take this value which is wrong and bit-shift in the most significant bit we get the real number:
uint64(3709913335383984176) + 1<<63 = 12933285372238759984

So somehow the longdecoder seems to be dropping the left-most bit when encoding it as int64, at least when the value is >2^63, expected behaviour would be a negative int64 value.

**Comment by karrick** [comment]
Thanks for your concerns. I added some additional testing to ensure goavro encoder and decoder are encoding Varint values correctly, and also properly round-tripping the data, and the tests are working.

Could you please check your data source to ensure it's encoding the value correctly?

Another probably cause is that the source of the data needs to cast your source uint64 value to an int64 before it encodes it. As you know, Avro does not have unsigned integer values, but when a use-case requires it, we need to cast the uint into an int, send that value to the encoder, and reverse the process for decoded data.

Encode(int64(someUint64Value)) --> uint64(Decode(blob)
