### ISSUE TITLE
Support for optional field

### ISSUE THREAD

**Issue by pm-kartik-sura** [linkedin/goavro#6]
Does goavro support optional field? I am getting error 

field has no data and no default set, when I set the field to following
       {
		"name": "device",
    		"type":[ "null", "SomeType"]
	}

**Comment by pm-kartik-sura** [comment]
Sorry I got around it 
 {
		"name": "device",
    		"type":[ "null", "someType"],
		"default": null
	}

**Comment by karrick** [comment]
@pm-kartik-sura,

No problem. I'm glad you got it working. :)
