### ISSUE TITLE
latest revision broken with {"type": "fixed"} field data type

### ISSUE THREAD

**Issue by quipo** [linkedin/goavro#61]
Getting this error decoding an Avro record with a "fixed" UUID field with the latest revision (e790a7b24f6b44a335798be9d2e38f4596971a52):

```
non-recognised non-scalar(?) type goavro.Fixed for field.Datum (c): goavro.Fixed{Name:"com.xxxxxxx.xxxx.UUID", Value:[]uint8{0x12, 0x7f, 0xe9, 0xc0, 0x3b, 0x59, 0x41, 0xf5, 0x93, 0x6d, 0x77, 0x75, 0xeb, 0x84, 0xb3, 0xc7}}
```

This is the relevant section of the Avro schema:

```
            {
            "name": "messageId",
            "type": {
              "type": "fixed",
              "name": "UUID",
              "namespace": "com.xxxxxxx.xxxx",
              "size": 16
            },
            "doc": "A unique identifier for the message"
          },
```

**Comment by karrick** [comment]
Inserting the following test code does show that the Fixed type is decoded correctly. I have a following suspicion that your error condition is happening when the Fixed type is embedded in another type.

`diff --git a/codec_test.go b/codec_test.go
index c7647af..3dddc6c 100644
--- a/codec_test.go
+++ b/codec_test.go
@@ -55,6 +55,13 @@ func checkCodecDecoderResult(t *testing.T, schema string, bits []byte, datum int
 			if bytes.Compare(decoded.([]byte), datum.([]byte)) != 0 {
 				t.Errorf("Actual: %#v; Expected: %#v", decoded, datum)
 			}
+		case Fixed:
+			if actual, expected := decoded.(Fixed).Name, datum.(Fixed).Name; actual != expected {
+				t.Errorf("Actual: %#v; Expected: %#v", actual, expected)
+			}
+			if actual, expected := decoded.(Fixed).Value, datum.(Fixed).Value; bytes.Compare(actual, expected) != 0 {
+				t.Errorf("Actual: %#v; Expected: %#v", actual, expected)
+			}
 		default:
 			if decoded != datum {
 				t.Errorf("Actual: %v; Expected: %v", decoded, datum)
@@ -540,6 +547,23 @@ func TestCodecFixed(t *testing.T) {
 	checkCodecEncoderResult(t, schema, Fixed{Name: "fixed1", Value: []byte("happy")}, []byte("happy"))
 }
 
+func TestCodecFixedDecoder(t *testing.T) {
+	schema := `
+{
+    "name": "messageId",
+    "type": {
+        "type": "fixed",
+        "size": 16,
+        "name": "UUID",
+        "namespace": "com.example"
+    },
+    "doc": "A unique identifier for the message"
+}`
+	bits := []byte{0x12, 0x7f, 0xe9, 0xc0, 0x3b, 0x59, 0x41, 0xf5, 0x93, 0x6d, 0x77, 0x75, 0xeb, 0x84, 0xb3, 0xc7}
+	expected := Fixed{Name: "com.example.UUID", Value: bits}
+	checkCodecDecoderResult(t, schema, bits, expected)
+}
+
 func TestCodecNamedTypesCheckSchema(t *testing.T) {
 	schema := `{"name":"guid","type":{"type":"fixed","name":"fixed_16","size":16},"doc":"event unique id"}`
 	var err error
`

**Comment by karrick** [comment]
I'm happy to revisit this issue, but please re-open if the problem returns for you.

Although I highly recommend you take a look at the newer, more performant implementation of goavro at https://github.com/karrick/goavro
