### ISSUE TITLE
Invalid rows silently corrupted when writing via OCF

### ISSUE THREAD

**Issue by jamescrowley** [linkedin/goavro#70]
When writing an Avro file, the current implementation silently drops rows that do not meet the specified codec (for instance have a missing required field), without any error output.

I've tracked down the issue to here:
https://github.com/linkedin/goavro/blob/master/ocf_writer.go#L367

Unfortunately my level of Go experience means I'm not yet sure how to propose this be fixed, but I shall think about that...

**Comment by karrick** [comment]
Wow! I really appreciate your tracking this bug down to the line number. Given the comment in the source code, it's apparent that I wasn't sure how to handle this particular type of condition given that the encoder runs in a different go routine.

Having said that, the new goavro engine does not specifically use different go routines to process the data, and when an attempt is made to Append data to an OCF file that fails to encode, the library returns an error immediately.

I'm actually working on improving OCF handling a bit more before merging the new library source code back into this library, but feel free to take a look in the meantime. Although OCF API will change in the new version, it might be good enough to get you started.

https://github.com/karrick/goavro/blob/master/examples/fileWriter/main.go#L53

**Comment by karrick** [comment]
I'm closing this issue because it is resolved in the new library version.
