### ISSUE TITLE
No support for Type references / recursion ?

### ISSUE THREAD

**Issue by StarpTech** [linkedin/goavro#72]
Im trying to use the type `Error` in a nested field called `cause`

```go
package main

import (
	"bytes"
	"log"

	"github.com/linkedin/goavro"
)

func main() {

	recordSchemaJSON := `{
    "name": "Packet",
    "type": "record",
    "fields": [{
        "name": "error",
        "default": {},
        "type": [{
            "name": "Error",
            "type": "record",
            "fields": [{
                "name": "cause",
                "type": ["null", "Error"],
                "default": null
            }]
        }]
    }]
}]
}`

	codec, err := goavro.NewCodec(recordSchemaJSON)
	if err != nil {
		log.Fatal(err)
	}

	record, err := goavro.NewRecord(goavro.RecordSchema(recordSchemaJSON))
	if err != nil {
		log.Fatal(err)
	}

	bb := new(bytes.Buffer)
	if err = codec.Encode(bb, record); err != nil {
		log.Fatal(err)
	}

}

```

**Error**
```
E:\Repositorys\hemera-golang>go run main.go
2017/01/30 21:01:17 cannot build record (null namespace): record field ought to be codec: {name:map[] nullCodec:0xc042056960 booleanCodec:0xc0420569c0 intCodec:0xc042056a20 longCodec:0xc042056900 floatCodec:0xc042056a80 doubleCodec:0xc042056ae0 b
ytesCodec:0xc042056b40 stringCodec:0xc042056ba0}: cannot build union (null namespace): member ought to be decodable: %!s(MISSING): cannot build record (null namespace): record field ought to be codec: {name:map[] nullCodec:0xc042056960 booleanCod
ec:0xc0420569c0 intCodec:0xc042056a20 longCodec:0xc042056900 floatCodec:0xc042056a80 doubleCodec:0xc042056ae0 bytesCodec:0xc042056b40 stringCodec:0xc042056ba0}: cannot build union (null namespace): member ought to be decodable: %!s(MISSING): cann
ot build unknown: unknown type name: Error
exit status 1
```

## Can also reproduce it with the example on the avro specification page.
See [Apaceh Avro](https://avro.apache.org/docs/current/spec.html) "Complex Types" section.

**Example**

```go
package main

import (
	"bytes"
	"log"

	"github.com/linkedin/goavro"
)

func main() {

	recordSchemaJSON := `{
  "type": "record",
  "name": "LongList",                  
  "fields" : [
    {"name": "next", "type": ["null", "LongList"]}
  ]
}`

	codec, err := goavro.NewCodec(recordSchemaJSON)
	if err != nil {
		log.Fatal(err)
	}

	record, err := goavro.NewRecord(goavro.RecordSchema(recordSchemaJSON))
	if err != nil {
		log.Fatal(err)
	}

	record.Set("next", "null")

	bb := new(bytes.Buffer)
	if err = codec.Encode(bb, record); err != nil {
		log.Fatal(err)
	}

}
```

**Error**

```
E:\Repositorys\hemera-golang>go run main.go
2017/01/30 21:13:04 cannot build record (null namespace): record field ought to be codec: {name:map[] nullCodec:0xc042090450 booleanCodec:0xc0420904b0 intCodec:0xc042090510 longCodec:0xc0420903f0 floatCodec:0xc042090570 doubleCodec:0xc0420905d0 b
ytesCodec:0xc042090630 stringCodec:0xc042090690}: cannot build union (null namespace): member ought to be decodable: %!s(MISSING): cannot build unknown: unknown type name: LongList
exit status 1
```

**Comment by StarpTech** [comment]
Hi @karrick could you verify it? Thanks

**Comment by StarpTech** [comment]
@karrick is this project still maintained?

**Comment by karrick** [comment]
Dustin,

Yes, I still maintain goavro. Sadly between work and 5 kids, I don't always
get to respond right away.

Thanks for contributing. I'll take a peek at it now and get back to you as
soon as I can.

**Comment by StarpTech** [comment]
Hi @karrick no problem just want to send a ping. Thank you.

**Comment by vgraveto** [comment]
Hello,
I am also having problem using goavro.NewCodec with a valid Avro linked list implementation:
const originSchemaJSON = `
                {
                 "type": "record",
                  "name": "Origin",
                  "fields": [
                    {
                      "name": "URI",
                      "type": "string"
                    },
                    {
                      "name": "UserAgent",
                      "type": "string"
                    },
                    {
                      "name": "Timestamp",
                      "type": "string"
                    },
                    {
                      "name": "PreviousOrigin",
                       "type": ["null", "Origin"]
                    }
                  ]
                }
`

"Origin" is not been detected !!
Can anyone help with a solution ?

**Comment by karrick** [comment]
Dustin,

There's good news and there's bad news. First the bad news: I'm not too keen on continued support for this version of goavro today.

The good news? I rewrote the engine and have fixed the issue you raised along with many other little issues in the next version of goavro.

What? You want more good news? It's 2x faster to create Avro codec instances.

What? You want more good news? It's 3x faster to convert native Go data to binary Avro data for my test corpus.

What? You want more good news? It's 4x faster to convert binary Avro data to native Go data for my test corpus.

What? You want more good news? It consumes fewer bytes and makes fewer runtime memory allocations than the previous version of goavro.

What? You want more good news? It correctly handles all test schemas provided by the Apache Avro project, including ones which are self referencing or use recursion.

What do you mean, what's the downside? Why do people always assume there's a downside?

Well there is a downside. The new version uses byte slices rather than io.Readers and io.Writers to do its work, so there is a slightly different API. I started writing an API layer to convert previous v4 calls to new engine v5 calls, and there is still a performance improvement although not as much, in addition to the many bug fixes.

So, with that being said, are you interested in trying out the new version?

-Karrick

**Comment by StarpTech** [comment]
@karrick I want more good news! When is the new version available and in which repository?

**Comment by sbramin** [comment]
I'm at the start of a journey rewriting a python stack into Go to handle moving data around in Avro and need every ounce of performance I can get to complete a backfill of years of data so yes please I'll beta test.

**Comment by vgraveto** [comment]
@karrick I also like the good news. When can we put our hands-on the new version? Were can we find it? I am really needing to use recursion

**Comment by karrick** [comment]
@vgraveto, I just tested the schema you pasted above and it does work with the new goavro engine. I will update the documentation for the new engine, and post a link to it shortly.

It *should* be considered beta in terms of API stability is concerned. The encoding and decoding algorithms are heavily tested however, and have all the tests from the v4 engine, along with extra test cases lifted from the Apache Avro project C source code.

**Comment by karrick** [comment]
Oh, and I owe you all a super big apology. I have been super busy this past few weeks preparing my family for a move. We're now in the new house, and climbing through boxes that need to be unpacked, but at least I have a work area again. And Internet! :)

**Comment by StarpTech** [comment]
@karrick I can feel with you 🗡 Your sixth kid (internet) is back :stuck_out_tongue_winking_eye:

**Comment by karrick** [comment]
@StarpTech Would you object to my use of your example above in the documentation or testing code?

**Comment by StarpTech** [comment]
@karrick at the moment I'm very busy but I'm trying to check it at the weekend.

**Comment by vgraveto** [comment]
@karrick Great. Let me know when that version is available and I will test it in my real environment.

**Comment by karrick** [comment]
The new v5 engine is located at https://github.com/karrick/goavro

I'm updating OCF support to allow for opening an OCF file for appending, which I expect to change the OCF API quite a bit, but encoding and decoding data is stable to use.

**Comment by karrick** [comment]
I've labeled this issue as "Won't Fix" because it has been fixed in the library rewrite.
