### ISSUE TITLE
Does not implement default correctly

### ISSUE THREAD

**Issue by evanrichards** [linkedin/goavro#77]
From the 1.7.7 spec:
`default: A default value for this field, used when reading instances that lack this field (optional).`

Defaults are defined in the spec to be used in schema resolution between writer and readers schema when consuming. The implementation here is inserting the default value when a field is missing or has invalid data:
codec.go 651:
```
				if reflect.ValueOf(field.Datum).IsValid() {
					value = field.Datum
				} else if field.hasDefault {
					value = field.defval
				} else {
					return newEncoderError(friendlyName, "field has no data and no default set: %v", field.Name)
				}
```
One possible implementation is when the field is missing to insert null providing null is first in the types union.

**Comment by karrick** [comment]
You are correct, and that's exactly what I'm about to do.
