### ISSUE TITLE
Field names don't allow fully qualified names with periods.

### ISSUE THREAD

**Issue by arunmk** [linkedin/goavro#8]
When the example code server.go in linkedin/goavro/examples/net is run and the client (built from client.go) in the same directory is run, the server program crashes. This is because the timestamp field is set using the fully-qualified path in server.go:

```
98         // you can fully qualify the field name
99         someRecord.Set("com.example.timestamp", int64(1082196484))
```

I have a simple patch:

```
commit a0dd9adc255b38b733f66c0e8ce3f038eae5b2b2
Author: Arun M. Krishnakumar <xxxxxx@gmail.com>
Date:   Fri May 1 10:53:21 2015 -0700

    Allow fully qualified paths in field names.

diff --git a/name.go b/name.go
index bf32798..bd4efcb 100644
--- a/name.go
+++ b/name.go
@@ -85,7 +85,7 @@ func (e ErrInvalidName) Error() string {
 }

 func isRuneInvalidForFirstCharacter(r rune) bool {
-       if (r >= 'A' && r <= 'Z') || (r >= 'a' && r <= 'z') || r == '_' {
+       if (r >= 'A' && r <= 'Z') || (r >= 'a' && r <= 'z') || r == '_' || r == '.' {
                return false
        }
        return true
@@ -106,7 +106,7 @@ func checkName(s string) error {
                return &ErrInvalidName{"start with [A-Za-z_]"}
        }
        if strings.IndexFunc(s[1:], isRuneInvalidForOtherCharacters) != -1 {
-               return &ErrInvalidName{"have second and remaining characters contain only [A-Za-z0-9_]"}
+               return &ErrInvalidName{"have second and remaining characters contain only [A-Za-z0-9._]"}
        }
        return nil
 }
```

If you think the above is valid and complete, I can create a pull request that can be merged, or you could take the patch yourself.

**Comment by arunlw** [comment]
CC @karrick

**Comment by karrick** [comment]
Sorry folks. I have *not* abandoned this project, but my full time job has kept me pretty busy.

I noticed that namespaces are not implemented correctly. I started working on a fix. I'll take a look at the above patch when I get a minute. Thank you for your feedback!

**Comment by c0b** [comment]
ping @karrick just wonder if you or any other one at linkedin have a minute in 2017? just scan over current open issues

**Comment by karrick** [comment]
@c0b,

Please check out the newly rewritten version of this library at https://github.com/karrick/goavro

It properly handles records with fully qualified field names.

**Comment by c0b** [comment]
thanks for the update, that blowed away all the doubts on whether the project is abandoned.

On the API breaking changes for go libraries, I see many ones are using the gopkg services like https://gopkg.in/yaml.v2 would you like also make a point there https://gopkg.in/goavro.v2 to your personal repo?

**Comment by karrick** [comment]
I have absolutely used gopkg.in before and I think that's a great way to update the library and tell people in the main README.md file to use that in their projects until they can update to use the new API.

Thanks for the suggestion!

-Karrick
