### ISSUE TITLE
avro files are unreadable

### ISSUE THREAD

**Issue by evgenigourvitch** [linkedin/goavro#81]
Hey,

Starting commit c76fd5f406a25824fa23feea0b0d0a2daec58d13 the output files are unreadable by avro-tools-1.8.1.jar (http://www-us.apache.org/dist/avro/avro-1.8.1/java/avro-tools-1.8.1.jar), the following exception is being thrown:

> Exception in thread "main" org.apache.avro.AvroRuntimeException: java.io.EOFException
> 	at org.apache.avro.file.DataFileStream.next(DataFileStream.java:222)
> 	at org.apache.avro.tool.DataFileReadTool.run(DataFileReadTool.java:76)
> 	at org.apache.avro.tool.Main.run(Main.java:87)
> 	at org.apache.avro.tool.Main.main(Main.java:76)
> Caused by: java.io.EOFException
> 	at org.apache.avro.io.BinaryDecoder.ensureBounds(BinaryDecoder.java:473)
> 	at org.apache.avro.io.BinaryDecoder.readInt(BinaryDecoder.java:128)
> 	at org.apache.avro.io.BinaryDecoder.readString(BinaryDecoder.java:259)
> 	at org.apache.avro.io.ResolvingDecoder.readString(ResolvingDecoder.java:201)
> 	at org.apache.avro.generic.GenericDatumReader.readString(GenericDatumReader.java:430)
> 	at org.apache.avro.generic.GenericDatumReader.readString(GenericDatumReader.java:422)
> 	at org.apache.avro.generic.GenericDatumReader.readWithoutConversion(GenericDatumReader.java:180)
> 	at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:152)
> 	at org.apache.avro.generic.GenericDatumReader.readField(GenericDatumReader.java:240)
> 	at org.apache.avro.generic.GenericDatumReader.readRecord(GenericDatumReader.java:230)
> 	at org.apache.avro.generic.GenericDatumReader.readWithoutConversion(GenericDatumReader.java:174)
> 	at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:152)
> 	at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:144)
> 	at org.apache.avro.file.DataFileStream.next(DataFileStream.java:233)
> 	at org.apache.avro.file.DataFileStream.next(DataFileStream.java:220)

also, sourcing data from avro file into google's BQ table fails with the following error:

> Errors:
> gs://some_bucket/some_avro_file.avro: The Apache Avro library failed to read data with the follwing error: EOF reached (error code: invalid)

test function we used to reproduce the issue:
```

type someKey struct {
        str1, str2, str3, str4 string
}

type someValue struct {
        someVal1               int64
}

func TestCreateFile(t *testing.T) {
	testData := []someKey{
		someKey{str1: `1`, str2: `1`, str3: `1`, str4: `1`},
		someKey{str1: `2`, str2: `2`, str3: `2`, str4: `2`},
		someKey{str1: `3`, str2: `3`, str3: `3`, str4: `3`},
		someKey{str1: `4`, str2: `4`, str3: `4`, str4: `4`},
	}
	codec, _ := goavro.NewCodec(schema)
	mp := make(map[someKey]*someValue)
	for r := 0; r < 100000; r++ {
		for i := range testData {
			d := testData[i]
			d.str1 = d.str1 + strconv.Itoa(r)
			mp[d] = &someValue{someVal1: 1}
		}
	}

	m := `test-` + time.Now().Format("200601020405")
	parseToAVRO(mp, m, codec, `/tmp/`+m+`.avro`)

}
```

thanks.

**Comment by neilepalmer** [comment]
I'm hitting exactly the same problem in the same scenario (import into BigQuery).  I'm new to Go so was still operating under the assumption that I was screwing up somewhere, but maybe not.

**Comment by neilepalmer** [comment]
Ok, I've fixed my problem.  I removed the compression from the codec.NewWriter() call and started seeing error messages/warnings around expecting a Float64 and only getting a Float32.  Once I fixed those, then the file imported into BigQuery correction (and avro-tools tojson worked as well).  Hope that helps.

**Comment by karrick** [comment]
@neilepalmer,

I'm glad you worked out the issue. I wish I had responded more quickly. At any rate, I have created a successor to this library which casts the native Go data types correctly when encoding. For instance, you can send `[]float64` to an encoder with the `{"type":"array","items":"float"}` schema. Similarly, you can send a Go `int` to an encoder with the `double` schema, provided the actual data would not lose precision when round tripped.

Please check out the new version at https://github.com/karrick/goavro

Once I finish OCF handling, I will work to migrate the new code over to this library.
