### ISSUE TITLE
Performance Expectations?

### ISSUE THREAD

**Issue by nemosupremo** [linkedin/goavro#84]
I'm working on my first project with Avro and I'm wondering what the encoding performance should be like. After trying debugging some performance issues in my application I came up with a small script:

```go
func clientTest2() {
	const schema = `{
	  "type": "record",
	  "name": "test_record",
	  "fields": [
	    {
	      "name": "name",
	      "type": "string"
	    },
	    {
	      "name": "metric",
	      "type": [
	        "int",
	        "null"
	      ]
	    }
	  ]
	}`

	{
		var codec goavro.Codec
		if c, err := goavro.NewCodec(schema); err == nil {
			codec = c
		} else {
			panic(err)
		}
		recordSchema := goavro.RecordSchema(schema)

		start := time.Now()
		for i := 0; i < 1000000; i++ {

			if someRecord, err := goavro.NewRecord(recordSchema); err == nil {

				i := 5
				if err := someRecord.Set("name", fmt.Sprintf("i_%d", i)); err != nil {
					log.Warnf("Set Error: %v", err)
				}
				if err := someRecord.Set("metric", int32(i)); err != nil {
					log.Warnf("Set Error: %v", err)
				}
				codec.Encode(ioutil.Discard, someRecord)
				/*
					if err := s.Write(someRecord); err != nil {
						log.Warnf("Write Error: %v", err)
						os.Exit(1)
					}
				*/
			} else {
				log.Warnf("NewRecord Error: %v", err)
				os.Exit(1)
			}
		}
		fmt.Printf("Avro Bench took %v\n", time.Now().Sub(start))
	}

	{
		var metric struct {
			Name   string `json:"string"`
			Metric int    `json:"metric"`
		}
		start := time.Now()
		for i := 0; i < 1000000; i++ {

			i := 5
			metric.Name = fmt.Sprintf("i_%d", i)
			metric.Metric = i
			json.Marshal(metric)
			/*
				if err := s.Write(someRecord); err != nil {
					log.Warnf("Write Error: %v", err)
					os.Exit(1)
				}
			*/

		}
		fmt.Printf("JSON Bench took %v\n", time.Now().Sub(start))
	}

}
```

On my local Machine (MacBook Pro (Retina, 13-inch, Early 2015) 2.7 GHz Intel Core i5) I get the following results:

```
$ go run ./cmd/main.go -tc
Avro Bench took 3.052033713s
JSON Bench took 982.483477ms
```

Where Avro consistently clocks in half as fast as the standard JSON library. Is this expected? Should I be creating `NewRecords` for every loop?

**Comment by karrick** [comment]
Thanks for the question. You don't _need_ to do that. Usually I recommend reusing the same goavro.Record over and over.

However, since we're talking about performance, please take a look at my new version of goavro library. On hefty payloads at LinkedIn I see 3x encoding performance using it, and 4x decoding performance while using it. It also corrects a number of issues in this library.

https://github.com/karrick/goavro

In the new library, you do not need to create goavro.Record instances at all. Please take a look ad let me know if you have any questions.
